CREATE TABLE processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL,
    transaction_id VARCHAR(128),
    processing_status VARCHAR(32) NOT NULL,
    sanitized_raw_payload JSONB,
    raw_payload_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_processed_events_event_id UNIQUE (event_id)
);

CREATE TABLE transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(128) NOT NULL,
    transaction_id VARCHAR(128) NOT NULL,
    customer_id VARCHAR(128) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    currency CHAR(3) NOT NULL,
    transaction_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    merchant_category VARCHAR(80) NOT NULL,
    country CHAR(2),
    channel VARCHAR(64),
    merchant_id VARCHAR(128),
    merchant_name VARCHAR(255),
    device_id VARCHAR(128),
    sanitized_raw_payload JSONB,
    raw_payload_expires_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_transactions_transaction_id UNIQUE (transaction_id),
    CONSTRAINT ck_transactions_amount_positive CHECK (amount > 0)
);

CREATE TABLE fraud_rules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    enabled BOOLEAN NOT NULL,
    severity VARCHAR(32) NOT NULL,
    score INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_fraud_rules_code UNIQUE (code),
    CONSTRAINT ck_fraud_rules_score_non_negative CHECK (score >= 0)
);

CREATE TABLE rule_evaluations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(128) NOT NULL,
    fraud_rule_id BIGINT,
    rule_code VARCHAR(100) NOT NULL,
    rule_name VARCHAR(255) NOT NULL,
    matched BOOLEAN NOT NULL,
    score_contribution INTEGER NOT NULL,
    explanation TEXT NOT NULL,
    evaluated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rule_evaluations_transactions
        FOREIGN KEY (transaction_id) REFERENCES transactions (transaction_id),
    CONSTRAINT fk_rule_evaluations_fraud_rules
        FOREIGN KEY (fraud_rule_id) REFERENCES fraud_rules (id) ON DELETE SET NULL,
    CONSTRAINT uk_rule_evaluations_transaction_rule UNIQUE (transaction_id, rule_code),
    CONSTRAINT ck_rule_evaluations_score_non_negative CHECK (score_contribution >= 0)
);

CREATE TABLE fraud_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id UUID NOT NULL,
    transaction_id VARCHAR(128) NOT NULL,
    customer_id VARCHAR(128) NOT NULL,
    account_id VARCHAR(128) NOT NULL,
    decision VARCHAR(32) NOT NULL,
    risk_score INTEGER NOT NULL,
    risk_level VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_fraud_alerts_alert_id UNIQUE (alert_id),
    CONSTRAINT fk_fraud_alerts_transactions
        FOREIGN KEY (transaction_id) REFERENCES transactions (transaction_id),
    CONSTRAINT ck_fraud_alerts_risk_score_non_negative CHECK (risk_score >= 0)
);

CREATE INDEX idx_processed_events_transaction_id ON processed_events (transaction_id);
CREATE INDEX idx_processed_events_created_at ON processed_events (created_at);
CREATE INDEX idx_processed_events_raw_payload_expires_at ON processed_events (raw_payload_expires_at);

CREATE INDEX idx_transactions_customer_id ON transactions (customer_id);
CREATE INDEX idx_transactions_account_id ON transactions (account_id);
CREATE INDEX idx_transactions_created_at ON transactions (created_at);
CREATE INDEX idx_transactions_raw_payload_expires_at ON transactions (raw_payload_expires_at);

CREATE INDEX idx_fraud_rules_enabled ON fraud_rules (enabled);
CREATE INDEX idx_fraud_rules_updated_at ON fraud_rules (updated_at);

CREATE INDEX idx_rule_evaluations_transaction_id ON rule_evaluations (transaction_id);
CREATE INDEX idx_rule_evaluations_matched ON rule_evaluations (matched);
CREATE INDEX idx_rule_evaluations_created_at ON rule_evaluations (created_at);

CREATE INDEX idx_fraud_alerts_customer_id ON fraud_alerts (customer_id);
CREATE INDEX idx_fraud_alerts_account_id ON fraud_alerts (account_id);
CREATE INDEX idx_fraud_alerts_transaction_id ON fraud_alerts (transaction_id);
CREATE INDEX idx_fraud_alerts_risk_level ON fraud_alerts (risk_level);
CREATE INDEX idx_fraud_alerts_created_at ON fraud_alerts (created_at);
CREATE INDEX idx_fraud_alerts_customer_date ON fraud_alerts (customer_id, created_at);
CREATE INDEX idx_fraud_alerts_account_date ON fraud_alerts (account_id, created_at);
CREATE INDEX idx_fraud_alerts_risk_level_date ON fraud_alerts (risk_level, created_at);
